/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harriserpentryprogram;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author zacha
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form fmrMain
     */
    public frmMain() {
        initComponents();
        resetLists();
    }
    PaymentHandler ph = new PaymentHandler();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPayment = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFeeAmount = new javax.swing.JTextField();
        btnAddPay = new javax.swing.JButton();
        btnAddFee = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPayments = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFees = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstTransactions = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        btnApplyPayments = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtFeeName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPayment.setText("100");

        jLabel1.setText("Payment Amount:");

        jLabel2.setText("Fee Amount:");

        txtFeeAmount.setText("50");
        txtFeeAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeeAmountActionPerformed(evt);
            }
        });

        btnAddPay.setText("Add Payment");
        btnAddPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPayActionPerformed(evt);
            }
        });

        btnAddFee.setText("Add Fee");
        btnAddFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFeeActionPerformed(evt);
            }
        });

        jLabel3.setText("Payments:");

        jLabel4.setText("Fees:");

        lstPayments.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstPayments);

        lstFees.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstFees);

        lstTransactions.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstTransactions);

        jLabel5.setText("Transactions:");

        btnApplyPayments.setText("Apply All Payments");
        btnApplyPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyPaymentsActionPerformed(evt);
            }
        });

        btnReset.setText("Reset Everything");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel6.setText("Fee Name:");

        txtFeeName.setText("Fee A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApplyPayments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFeeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3)
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFeeName, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddFee)
                                .addGap(107, 107, 107))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddPay)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnAddPay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFeeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnAddFee)
                    .addComponent(jLabel6)
                    .addComponent(txtFeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApplyPayments)
                    .addComponent(btnReset))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void resetLists(){
        DefaultListModel<String> dlm = new DefaultListModel<>();
        lstFees.setModel(dlm);
        lstTransactions.setModel(dlm);
        lstPayments.setModel(dlm);
        ph.resetLists();
    }
    private static DefaultListModel buildPayments(ArrayList<Payment> arr){
        DefaultListModel<String> dlm = new DefaultListModel<>();
        arr.forEach((n)->{dlm.addElement(Float.toString(n.getAmount()));});
        return dlm;
    }
    private static DefaultListModel buildFees(ArrayList<Fee> arr){
        DefaultListModel<String> dlm = new DefaultListModel<>();
        arr.forEach((n)->{dlm.addElement(n.getName()+": "+Float.toString(n.getAmount()));});
        return dlm;
    }
    private static DefaultListModel buildTransactions(ArrayList<Transaction> arr){
        DefaultListModel<String> dlm = new DefaultListModel<>();
        arr.forEach((n)->{dlm.addElement(Float.toString(n.getAmount())+" for "+n.getFee().getName());});
        return dlm;
    }
    private void txtFeeAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeeAmountActionPerformed
        
    }//GEN-LAST:event_txtFeeAmountActionPerformed

    private void btnAddFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFeeActionPerformed
        //If there are already transactions listed, prompt the user to clear the display before proceeding with adding more fees and payments
        if (lstTransactions.getModel().getSize()!=0){
            int selection = JOptionPane.showConfirmDialog(this,"Clear listed payments, fees, and transactions to add more?","Clear screen to proceed?",JOptionPane.YES_NO_OPTION);
            if (selection == JOptionPane.YES_OPTION){
                resetLists();
            }else{
                return;
            }
        }
        try{
            float fa = Float.parseFloat(txtFeeAmount.getText());
            String fn = txtFeeName.getText();
            ph.addFee(new Fee(fa,fn));          
        }catch(Exception e){
            //System.err.println(e);
            JOptionPane.showMessageDialog(this, "User input could not be parsed to decimal format.\nCheck input and try again!");
        }
        lstFees.setModel(buildFees(ph.getFees()));
    }//GEN-LAST:event_btnAddFeeActionPerformed

    private void btnAddPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPayActionPerformed
        //If there are already transactions listed, prompt the user to clear the display before proceeding with adding more fees and payments
        if (lstTransactions.getModel().getSize()!=0){
            int selection = JOptionPane.showConfirmDialog(this,"Clear listed payments, fees, and transactions to add more?","Clear screen to proceed?",JOptionPane.YES_NO_OPTION);
            if (selection == JOptionPane.YES_OPTION){
                resetLists();
            }else{
                return;
            }
        }
        try{
            float p = Float.parseFloat(txtPayment.getText());
            ph.addPayment(new Payment(p));
        }catch(Exception e){
            //System.err.println(e);
            JOptionPane.showMessageDialog(this, "User input could not be parsed to decimal format.\nCheck input and try again!");
        }
        lstPayments.setModel(buildPayments(ph.getPayments()));        
    }//GEN-LAST:event_btnAddPayActionPerformed

    private void btnApplyPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyPaymentsActionPerformed
        if (lstTransactions.getModel().getSize()!=0){
            JOptionPane.showMessageDialog(this,"Transactions have already been built for the given lists");
            return;  
        }
        ph.applyPayments();
        lstTransactions.setModel(buildTransactions(ph.getTransactions()));
    }//GEN-LAST:event_btnApplyPaymentsActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetLists();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFee;
    private javax.swing.JButton btnAddPay;
    private javax.swing.JButton btnApplyPayments;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstFees;
    private javax.swing.JList<String> lstPayments;
    private javax.swing.JList<String> lstTransactions;
    private javax.swing.JTextField txtFeeAmount;
    private javax.swing.JTextField txtFeeName;
    private javax.swing.JTextField txtPayment;
    // End of variables declaration//GEN-END:variables
}
